# Generated by Django 4.1.5 on 2023-03-12 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reuseBank', '0002_rename_reusebank_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
