<<<<<<< HEAD
# Generated by Django 4.1.6 on 2023-02-21 10:50
=======
# Generated by Django 4.0.2 on 2023-02-17 15:32
>>>>>>> bd1cc5184b7482fbbe33e34aaef14deef4f10dca

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=5)),
                ('more', models.URLField()),
            ],
        ),
    ]
