# Generated by Django 4.0.2 on 2023-03-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='more',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
