<<<<<<< HEAD
# Generated by Django 4.1.6 on 2023-02-21 10:50
=======
# Generated by Django 4.0.2 on 2023-02-19 21:00
>>>>>>> bd1cc5184b7482fbbe33e34aaef14deef4f10dca

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=150, unique=True)),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
