# Generated by Django 4.1.5 on 2023-03-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_tag_delete_post_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='affiliation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='blog',
            name='firstName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='lastName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
