# Generated by Django 4.1.5 on 2023-03-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_affiliation_blog_email_blog_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='conTitle',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
