# Generated by Django 4.1.5 on 2023-03-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_contitle_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='contribution',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='otherContribution',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='otherRole',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
